services:
  aapanel:
    build: .
    container_name: aapanel-docker
    ports:
      - "7800:7800"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - aapanel-data:/www
    restart: unless-stopped

volumes:
  aapanel-data:
